test:
  workers:
    number: 4
  rounds:
    - label: load.
      txNumber: 100000
      rateControl:
          type: linear-rate
          opts:
            startingTps: 250
            finishingTps: 1000
      workload:
        module: benchmarks/samples/fabric/smallbank/load.js
        arguments:
          txnPerBatch: 1
    - label: mixed.
      txNumber: 100000
      rateControl:
          type: linear-rate
          opts:
            startingTps: 250
            finishingTps: 1000
      workload:
        module: benchmarks/samples/fabric/smallbank/mixed.js
        arguments:
          queryRatio: 0.1
          txnPerBatch: 1
monitors:
  resource:
  - module: docker
    options:
      interval: 1
      containers: 
      - peer0.org1.example.com
      - http://172.19.127.240:2375/peer0.org1.example.com
      - peer0.org2.example.com
      - http://172.19.127.234:2375/peer0.org2.example.com
      - peer0.org3.example.com
      - http://172.19.127.233:2375/peer0.org3.example.com
      - peer0.org4.example.com
      - http://172.19.127.236:2375/peer0.org4.example.com
      - orderer1.example.com
      - http://172.19.127.238:2375/orderer1.example.com
      - orderer2.example.com
      - http://172.19.127.239:2375/orderer2.example.com
      - orderer3.example.com
      - http://172.19.127.232:2375/orderer3.example.com
      - orderer4.example.com
      - http://172.19.127.235:2375/orderer4.example.com
    charting:
      bar:
        metrics: [all]
